apiVersion: bindplane.observiq.com/v1beta
kind: Configuration
metadata:
  name: otlp
  labels:
    platform: macos
    app: cabin
spec:
  contentType: text/yaml
  raw: >
    # sample config from https://opentelemetry.io/docs/collector/configuration/

    receivers:
      otlp:
        protocols:
          grpc:
          http:

    processors:
      batch:

    exporters:
      otlp:
        endpoint: otelcol:4317

    extensions:
      health_check:
      pprof:
      zpages:

    service:
      extensions: [health_check,pprof,zpages]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
  selector:
    matchLabels:
      "configuration": otlp
