apiVersion: bindplane.observiq.com/v1beta
kind: DestinationType
metadata:
  name: googlecloud
  displayName: Google Cloud
  icon: /icons/destinations/google-cloud-logging.svg
spec:
  parameters:
  metrics:
    processors: |
      - normalizesums:
      - batch:
  logs+traces:
    processors: |
      - batch:
  logs+metrics+traces:
    exporters: |
      - googlecloud:
